version: 2.1

orbs:
  codacy: codacy/base@0.0.8

references:

  docker_environment_defaults: &docker_environment_defaults
    # Customize the JVM to read correct memory values
    JAVA_OPTS: '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1'

  host_environment_defaults: &host_environment_defaults
    # Customize the JVM maximum heap limit
    JAVA_OPTS: -Xss256m -Xmx6144m

  default_java_job: &default_java_job
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          <<: *docker_environment_defaults
    working_directory: ~/workdir

  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - sbt-ivy2-dependencies-1.0.2-{{ checksum "/tmp/dependencies.cache.tmp" }}
        - sbt-ivy2-dependencies-1.0.2

  setup_dependencies_key: &setup_dependencies_key
    run:
      name: Generate cache key
      command: |
        shasum build.sbt \
          project/plugins.sbt \
          project/build.properties > /tmp/dependencies.cache.tmp

  load_docker_file: &load_docker_file
    run:
      name: Load docker from file
      command: docker load --input ~/tool_image.tar


jobs:

  setup_plugins_test:
    machine: true
    environment:
      <<: *host_environment_defaults
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - *setup_dependencies_key
      - *restore_dependencies
      - run:
          name: Clone test project
          working_directory: ~/
          command: |
            (git -C ~/codacy-plugins-test fetch --all &&
              git -C ~/codacy-plugins-test reset --hard origin/master) ||
                git clone git://github.com/codacy/codacy-plugins-test.git ~/codacy-plugins-test
      - run:
          name: Compile test project
          working_directory: ~/codacy-plugins-test
          command: sbt compile
      - save_cache:
          key: sbt-ivy2-dependencies-1.0.2-{{ checksum "/tmp/dependencies.cache.tmp" }}
          paths:
            - "~/codacy-plugins-test"
            - "~/codacy-plugins-test/target"
            - "~/codacy-plugins-test/project/target"
            - "~/codacy-plugins-test/project/project"
      - persist_to_workspace:
          root: ~/
          paths:
            - codacy-plugins-test

  publish_local:
    machine: true
    environment:
      <<: *host_environment_defaults
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - *setup_dependencies_key
      - *restore_dependencies
      - run:
          name: Compile
          command: sbt 'set version in Docker := "latest"' "set name := \"$CIRCLE_PROJECT_REPONAME\"" docker:publishLocal
      - run:
          name: Save docker to file
          command: docker save --output ~/tool_image.tar $CIRCLE_PROJECT_REPONAME:latest
      - persist_to_workspace:
          root: ~/
          paths:
            - tool_image.tar

  plugins_test_json:
    machine: true
    environment:
      <<: *host_environment_defaults
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - *setup_dependencies_key
      - *restore_dependencies
      - *load_docker_file
      - run:
          name: Test json
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.ignore.descriptions=true "runMain codacy.plugins.DockerTest json $CIRCLE_PROJECT_REPONAME:latest"

  plugins_test_patterns:
    machine: true
    environment:
      <<: *host_environment_defaults
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - *setup_dependencies_key
      - *restore_dependencies
      - *load_docker_file
      - run:
          name: Test patterns
          working_directory: ~/codacy-plugins-test
          command: sbt -Dcodacy.tests.noremove=true -Dcodacy.tests.threads=8 "runMain codacy.plugins.DockerTest pattern $CIRCLE_PROJECT_REPONAME:latest"

  publish_docker_hub:
    machine: true
    environment:
      <<: *host_environment_defaults
    working_directory: ~/workdir
    steps:
      - attach_workspace:
          at: ~/
      - *setup_dependencies_key
      - *restore_dependencies
      - *load_docker_file
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker tag $CIRCLE_PROJECT_REPONAME codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)
            docker push codacy/$CIRCLE_PROJECT_REPONAME:latest
            docker push codacy/$CIRCLE_PROJECT_REPONAME:$(cat .version)

workflows:
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: populate_cache
          cmd: sbt update
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: check_fmt
          cmd: sbt ";scalafmt::test;test:scalafmt::test;sbt:scalafmt::test"
          requires:
            - populate_cache
      - codacy/sbt:
          name: compile
          cmd: sbt ";compile;test:compile"
          requires:
            - check_fmt
      - setup_plugins_test:
          requires:
            - codacy/checkout_and_version
      - publish_local:
          requires:
            - check_fmt
      - plugins_test_json:
          requires:
            - compile
            - publish_local
            - setup_plugins_test
      - plugins_test_patterns:
          requires:
            - compile
            - publish_local
            - setup_plugins_test
      - publish_docker_hub:
          context: CodacyDocker
          requires:
            - plugins_test_json
            - plugins_test_patterns
          filters:
            branches:
              only:
              - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_docker_hub